-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 18:41:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema teamtasker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teamtasker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teamtasker` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `teamtasker` ;

-- -----------------------------------------------------
-- Table `teamtasker`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamtasker`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamtasker`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamtasker`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `perfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `perfil`),
  INDEX `fk_Usuario_Perfil1_idx` (`perfil` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Perfil1`
    FOREIGN KEY (`perfil`)
    REFERENCES `teamtasker`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamtasker`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamtasker`.`Proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `dateIn` DATETIME NOT NULL,
  `dateEnd` DATETIME NOT NULL,
  `progreso` DOUBLE NULL,
  `duracion` INT NULL,
  `estado` VARCHAR(70) NOT NULL,
  `admin_proyecto` INT NOT NULL,
  PRIMARY KEY (`idProyecto`, `admin_proyecto`),
  UNIQUE INDEX `idProyecto_UNIQUE` (`idProyecto` ASC) VISIBLE,
  INDEX `fk_Proyecto_Usuario1_idx` (`admin_proyecto` ASC) VISIBLE,
  CONSTRAINT `fk_Proyecto_Usuario1`
    FOREIGN KEY (`admin_proyecto`)
    REFERENCES `teamtasker`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamtasker`.`Etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamtasker`.`Etiqueta` (
  `idEtiqueta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `proyecto` INT NOT NULL,
  PRIMARY KEY (`idEtiqueta`, `proyecto`),
  INDEX `fk_Etiqueta_Proyecto1_idx` (`proyecto` ASC) VISIBLE,
  CONSTRAINT `fk_Etiqueta_Proyecto1`
    FOREIGN KEY (`proyecto`)
    REFERENCES `teamtasker`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamtasker`.`Prioridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamtasker`.`Prioridad` (
  `idPrioridad` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idPrioridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamtasker`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamtasker`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `proyecto` INT NOT NULL,
  `admin_grupo` INT NOT NULL,
  `completada` TINYINT NOT NULL,
  `dateIn` DATETIME NOT NULL,
  `dateEnd` DATETIME NOT NULL,
  `progreso` DOUBLE NULL,
  `duracion` INT NULL,
  `estado` VARCHAR(70) NOT NULL,
  `etiqueta` INT NOT NULL,
  `prioridad` INT NOT NULL,
  PRIMARY KEY (`idGrupo`, `proyecto`, `admin_grupo`, `etiqueta`, `prioridad`),
  INDEX `fk_Grupo_Proyecto_idx` (`proyecto` ASC) VISIBLE,
  INDEX `fk_Grupo_Usuario1_idx` (`admin_grupo` ASC) VISIBLE,
  INDEX `fk_Grupo_Etiqueta1_idx` (`etiqueta` ASC) VISIBLE,
  INDEX `fk_Grupo_Prioridad1_idx` (`prioridad` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_Proyecto`
    FOREIGN KEY (`proyecto`)
    REFERENCES `teamtasker`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Usuario1`
    FOREIGN KEY (`admin_grupo`)
    REFERENCES `teamtasker`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Etiqueta1`
    FOREIGN KEY (`etiqueta`)
    REFERENCES `teamtasker`.`Etiqueta` (`idEtiqueta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Prioridad1`
    FOREIGN KEY (`prioridad`)
    REFERENCES `teamtasker`.`Prioridad` (`idPrioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamtasker`.`TareaUnitaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamtasker`.`TareaUnitaria` (
  `idTareaUnitaria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `grupo` INT NOT NULL,
  `usuario` INT NOT NULL,
  `dateIn` DATETIME NULL,
  `dateEnd` DATETIME NULL,
  `progreso` DOUBLE NULL,
  `duracion` INT NULL,
  `hito` TINYINT NULL,
  `etiqueta` INT NOT NULL,
  `prioridad` INT NOT NULL,
  PRIMARY KEY (`idTareaUnitaria`, `grupo`, `usuario`, `etiqueta`, `prioridad`),
  INDEX `fk_TareaUnitaria_Grupo1_idx` (`grupo` ASC) VISIBLE,
  INDEX `fk_TareaUnitaria_Usuario1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_TareaUnitaria_Etiqueta1_idx` (`etiqueta` ASC) VISIBLE,
  INDEX `fk_TareaUnitaria_Prioridad1_idx` (`prioridad` ASC) VISIBLE,
  CONSTRAINT `fk_TareaUnitaria_Grupo1`
    FOREIGN KEY (`grupo`)
    REFERENCES `teamtasker`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TareaUnitaria_Usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `teamtasker`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TareaUnitaria_Etiqueta1`
    FOREIGN KEY (`etiqueta`)
    REFERENCES `teamtasker`.`Etiqueta` (`idEtiqueta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TareaUnitaria_Prioridad1`
    FOREIGN KEY (`prioridad`)
    REFERENCES `teamtasker`.`Prioridad` (`idPrioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teamtasker`.`Grupo_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teamtasker`.`Grupo_has_Usuario` (
  `grupo` INT NOT NULL,
  `Grupo_Proyecto` INT NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`grupo`, `Grupo_Proyecto`, `usuario`),
  INDEX `fk_Grupo_has_Usuario_Usuario1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_Grupo_has_Usuario_Grupo1_idx` (`grupo` ASC, `Grupo_Proyecto` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_has_Usuario_Grupo1`
    FOREIGN KEY (`grupo` , `Grupo_Proyecto`)
    REFERENCES `teamtasker`.`Grupo` (`idGrupo` , `proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Usuario_Usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `teamtasker`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
